apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: rippal-base

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - tcp-service.yaml
  - pvc.yaml
  - ingress.yaml
  - secret.yaml

commonLabels:
  app: rippal
  version: v1.0.0

images:
  - name: docker4zerocool/rippal
    newTag: latest
